language: java
cache:
  directories:
    - $HOME/.m2
build:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean verify

notifications:
  email:
    - mvmarkon@gmail.com
    - mverdecanna@gmail.com
test:
  - mvn test -B
